--- drivers/media/platform/msm/camera_v2/sensor/actuator/Makefile
+++ drivers/media/platform/msm/camera_v2/sensor/actuator/Makefile
@@ -1,4 +1,5 @@
 ccflags-y += -Idrivers/media/platform/msm/camera_v2
+ccflags-y += -Idrivers/media/platform/msm/camera_v2/common
 ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
 ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
 obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
