--- drivers/media/platform/msm/camera_v2/sensor/flash/Makefile
+++ drivers/media/platform/msm/camera_v2/sensor/flash/Makefile
@@ -1,4 +1,5 @@
 ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
 ccflags-y += -Idrivers/media/platform/msm/camera_v2
+ccflags-y += -Idrivers/media/platform/msm/camera_v2/common
 ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
 obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o
