--- drivers/media/platform/msm/camera_v2/common/Makefile
+++ drivers/media/platform/msm/camera_v2/common/Makefile
@@ -1,2 +1,2 @@
 ccflags-y += -Idrivers/media/platform/msm/camera_v2/
-obj-$(CONFIG_MSMB_CAMERA) += cam_smmu_api.o cam_hw_ops.o
+obj-$(CONFIG_MSMB_CAMERA) += msm_camera_io_util.o cam_smmu_api.o cam_hw_ops.o
